---
title: "Getting started with the workshop"
author: Christophe Vanderaa^[vanderaa.christophe@gmail.com]
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Workshop Title

Authors:
    Christophe Vanderaa^[UGhent],
    Lieven Clement^[UGhent],
    Laurent Gatto^[UCLouvain].
    <br/>
Last modified: \today.

## Overview

### Description

Mass spectrometry (MS) has become a method of choice for exploring the
proteome landscape that drives cellular functions. While technological
advancements have significantly increased the sensitivity of MS
instruments, obtaining reliable statistical results from these data
remains a challenging and often tedious task. Many researchers
continue to rely on ad-hoc analysis workflows due to a lack of clear
guidelines, which can lead to violations of key statistical
assumptions. In this workshop, we will offer a hands-on introduction
to the msqrob2 package that provides a set of rigorously validated and
benchmarked statistical workflows for MS-based proteomics. These
workflows are built on the QFeatures framework for data processing. We
will begin by familiarising participants with the input data format
and the QFeatures data structure. From there, we will walk through the
minimal data processing steps required prior to statistical modelling,
explaining when and why each step is necessary. Next, we’ll explore
the sources of variation inherent in proteomics data, highlighting
their hierarchical structure and demonstrating how linear mixed models
can properly account for these complexities. The modelling process
will be carried out using msqrob2, which offers additional advantages
such as robust and stabilised parameter estimation. Finally, we will
demonstrate how to translate biological questions into hypothesis
tests and how to prioritise proteomic markers that change in response
to a condition of interest. Depending on the progress of the group, we
will also briefly explore the emerging field of single-cell
proteomics, discussing the additional challenges posed by these data.
This workshop is designed for proteomics researchers who want to learn
how to analyse their data using reproducible and statistically sound
workflows, as well as for omics data analysts interested in expanding
their skill set to include proteomics.



Along with the topic of your workshop, include how students can expect
to spend their time. For the description may also include information
about what type of workshop it is (e.g. instructor-led live demo, lab,
lecture + lab, etc.). Instructors are strongly recommended to provide
completely worked examples for lab sessions, and a set of stand-alone
notes that can be read and understood outside of the workshop.

### Pre-requisites

* Basic knowledge of R syntax
* Familiarity with the `SummarizedExperiment` class
* Familiarity with omics data analysis
* Familiarity with statistical testing

Relevant background reading for the workshop:

* Vandenbulcke S, Vanderaa C, Crook O, Martens L, Clement L. 
  Msqrob2TMT: Robust linear mixed models for inferring differential
  abundant proteins in labeled experiments with arbitrarily complex
  design. Mol Cell Proteomics. 2025;24(7):101002.
  [Link to paper](https://doi.org/10.1016/j.mcpro.2025.101002);
  [Link to preprint](https://www.biorxiv.org/content/10.1101/2024.03.29.587218v1).
* The [`QFeatures` introduction vignette](https://rformassspectrometry.github.io/QFeatures/articles/QFeatures.html)
* Goeminne LJE, Gevaert K, Clement L. Peptide-level Robust Ridge 
  Regression Improves Estimation, Sensitivity, and Specificity in 
  Data-dependent Quantitative Label-free Shotgun Proteomics. Mol Cell
  Proteomics. 2016;15(2):657-668.
  [Link to paper](https://doi.org/10.1074/mcp.M115.055897);

### Participation

Describe how students will be expected to participate in the workshop.

### _R_ / _Bioconductor_ packages used

- msqrob2
- BiocFileCache
- BiocParallel
- ggplot2
- patchwork
- dplyr
- ExploreModelMatrix

### Time outline

| Activity                       | Time |
|--------------------------------|------|
| Introduction and setup         | 10m  |
| The `QFeatures` data class     | 20m  |
| Data preprocessing             | 15m  |
| Break                          | 15m  |
| Modelling sources of variation | 20m  |
| Hypothesis testing             | 20m  |
| Wrap up                        |  5m  |

### Workshop goals and objectives

List "big picture" student-centered workshop goals and learning
objectives. Learning goals and objectives are related, but not the
same thing. These goals and objectives will help some people to decide
whether to attend the conference for training purposes, so please make
these as precise and accurate as possible.

*Learning goals* are high-level descriptions of what
participants will learn and be able to do after the workshop is
over. *Learning objectives*, on the other hand, describe in very
specific and measurable terms specific skills or knowledge
attained. The [Bloom's Taxonomy](#bloom) may be a useful framework
for defining and describing your goals and objectives, although there
are others.

### Learning goals

Some examples:

* describe how to...
* identify methods for...
* understand the difference between...

### Learning objectives

* analyze xyz data to produce...
* create xyz plots
* evaluate xyz data for artifacts

## Workshop

Divide the workshop into sections (`## A Section`). Include
fully-evaluated _R_ code chunks. Develop exercises and solutions, and
anticipate that your audience will walk through the code with you, or
work on the code independently -- do not be too ambitious in the
material that you present.